###  Creates a new user
POST http://localhost:4004/api/accounts/users/create
Content-type: application/json
Authorization: Bearer {{token}}

{
  "email":"edixon34@gmail.com",
  "password": "12345678",
  "firstName": "doctor",
  "lastName": "puto",
  "type": "USER_DOCTOR",
  "dateOfBirth": "1999-10-28",
  "addressId": 1
}
