### Creates new patient entity
POST http://localhost:4000/patients
Content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "with kafka",
    "email": "analytics@example.com",
    "address": "piar avenida 33",
    "dateOfBirth": "1999-02-10",
    "registeredDate": "2025-11-28"
}

###