### POST create a tenant
POST http://localhost:4004/api/accounts/tenants/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tenant 2",
    "email": "tenant4@gmail.com"
}
###