server:
 port: 4004

spring:
  cloud:
    gateway:
      routes:
        - id: patient-service-route
          uri: http://patient-service:4009
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        # No JWT Validation routes (must be first one before the general one)
        - id: account-auth-route
          uri: http://account-service:4010
          predicates:
            - Path=/api/accounts/auth/**
          filters:
            - StripPrefix=1
        # JWT Validations (outside of /accounts/auth)
        - id: account-service-route
          uri: http://account-service:4010
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=1
            - JwtValidation


        - id: api-docs-account-route
          uri: http://account-service:4010
          predicates:
            - Path=/api-docs/login
          filters:
            - RewritePath=/api-docs/login,/v3/api-docs
      globalcors:
        cors-configurations:
          '[/**]': # Aplica a todas las rutas
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS # ¡Importante! El navegador hace una petición OPTIONS "preflight"
            allowedHeaders: "*" # O especifica cabeceras: Content-Type, Authorization, etc.
            allowCredentials: true # Poner a true si envías cookies o tokens de autorización (Authorization header). ¡OJO! Si pones true, NO puedes usar "*" en allowedOrigins.
            maxAge: 3600 # Tiempo en segundos que el navegador cachea la respuesta preflight OPTIONS (1 hora)
