### login request to retrieve a token
POST http://localhost:4004/api/accounts/auth/login
Content-type: application/json

{
    "email":"jesus2@test.com",
    "password": "password123"
}

> {% client.global.set("token", response.body.token) %}

